### PR TITLE
QT: Show miner type on block reward

### PR DESCRIPTION
**Pull request by ghost**
## TODO
- [x] strings
- [x] icon

### CODE REVIEW

**Comment by rmdfwqclmrkcvpbe** [comment]
@kazu3kazu3 Is there lovely icon?

**Review by kazu3kazu3 — DISMISSED** [review]

**Comment by rmdfwqclmrkcvpbe** [comment]
a
b

**Comment by ghost** [comment]
@kazu3kazu3 @NEETCOINProject @saboten-senpai ping

**Comment by ghost** [comment]
gggggggggg
ffffffffffffffff

**Review by kazu3kazu3 — DISMISSED** [review]

**Comment by ghost** [comment]
untitled

**Review by kazu3kazu3 — DISMISSED** [review]

**Review by kazu3kazu3 — DISMISSED** [review]

**Comment by ghost** [comment]
untitled

**Review by kazu3kazu3 — APPROVED** [review]

**Pull request merged**
